openapi: 3.0.0
info:
  title: social
  version: '1.0'
servers:
  - url: 'https://api.dev.icheck.com.vn/api/v1'
paths:
  '/scan/:barcode':
    get:
      summary: Scan barcode
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetail'
              examples: {}
      operationId: scan-products
      description: ''
      tags:
        - product
  /products:
    get:
      summary: Danh sách sản phẩm iCheck
      tags:
        - product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  rows:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductItem'
      operationId: get-products
      parameters:
        - schema:
            type: integer
          in: query
          name: limit
          description: ' '
        - schema:
            type: integer
          in: query
          name: offset
          description: ' '
        - schema:
            type: string
            example: '-id'
          in: query
          name: order
          description: sắp xếp
        - schema:
            type: number
          in: query
          name: owner_id
          description: 'là id của doanh nghiệp sở hữu '
        - schema:
            type: string
          in: query
          name: category_id
          description: 'id của danh mục '
        - schema:
            type: string
          in: query
          name: search
          description: 'Tìm kiếm theo tên hoặc mã barcode '
        - schema:
            type: string
          in: query
          name: enterprise_search
          description: 'Tìm theo tên hoặc mã doanh nghiệp sở hữu '
        - schema:
            type: string
          in: query
          name: ids
          description: 'nằm trong danh sách id, vd: 123,234,345 '
        - schema:
            type: string
          in: query
          name: not_ids
          description: 'ngoài trừ các id, vd: 123,234,345 '
        - schema:
            type: boolean
          in: query
          name: verified
          description: 'đã xác thực '
        - schema:
            type: string
            enum:
              - 1
              - 2
              - 3
          in: query
          name: scan_state
          description: 'trạng thái quét - 1: cho quét, 2: không cho quét, 3: ẩn do doanh nghiệp yêu cầu '
        - schema:
            type: number
            enum:
              - 1
              - 0
          in: query
          name: empty_image
          description: 'không có ảnh - 1: đúng, 2: sai '
        - schema:
            type: number
          in: query
          name: empty_name
          description: 'không có tên - 1: đúng, 2: sai '
        - schema:
            type: number
          in: query
          name: empty_owner
          description: 'không có doanh nghiệp sở hữu - 1: đúng, 2: sai '
        - schema:
            type: number
          in: query
          name: empty_price
          description: 'không có giá - 1: đúng, 2: sai '
        - schema:
            type: number
          in: query
          name: empty_category
          description: 'không thuộc danh mục - 1: đúng, 2: sai '
        - schema:
            type: boolean
          in: query
          name: visibled
          description: ẩn sản phẩm
        - schema:
            type: string
          in: query
          name: include
          description: include=detail - trả về giống detail
      description: Danh sách sản phẩm iCheck
  '/products/:id':
    get:
      summary: Lấy chi tiết sản phẩm thông qua ID
      tags:
        - product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetail'
      operationId: 'get-products-:id'
      description: Lấy chi tiết sản phẩm thông qua id
  '/products/barcode/:barcode':
    get:
      summary: Lấy sản phẩm qua barcode
      tags:
        - product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetail'
      operationId: get-products-barcode
      description: Lấy sản phẩm qua barcode
    parameters: []
  '/products/:product_id/related-products':
    get:
      summary: Danh sách sản phẩm liên quan
      tags:
        - product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  rows:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductItem'
      operationId: 'get-products-:product_id-related-products'
      parameters:
        - schema:
            type: integer
          in: query
          name: limit
          description: ''
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: string
          in: query
          name: order
          description: sắp xếp
        - schema:
            type: string
          in: query
          name: include
          description: 'incluide=detail : trả về giống detail'
      description: ''
components:
  schemas:
    ProductDetail:
      title: ProductDetail
      type: object
      description: Thông tin chi tiết sản phẩm
      x-examples:
        example-1: {}
      properties:
        id:
          type: integer
          description: |
            id của sản phẩm
        name:
          type: string
          description: tên của sản phẩm
        barcode:
          type: string
          description: mã barcode
        price:
          type: number
          description: giá cả
        image:
          type: string
          description: ảnh sản phẩm
        thumbnails:
          $ref: '#/components/schemas/Thumbnails'
        owner:
          $ref: '#/components/schemas/EnterpriseDetail'
        disable_contribution:
          type: boolean
          description: tắt tính năng đóng góp
        verified:
          type: boolean
          description: đã xác thực
        visibled:
          type: boolean
          description: ẩn sản phẩm
        informations:
          type: string
        review_count:
          type: integer
          description: Tổng lượt review
        question_count:
          type: integer
          description: Tổng số câu hỏi
        can_scan:
          type: boolean
        scan_count:
          type: integer
          description: Tổng lượt scan
        product_level_id:
          type: number
          description: id level nguồn tạo
        product_level_label:
          type: string
          description: tên nguồn tạo
        certification_content:
          type: string
        certificates:
          type: array
          items:
            type: string
        video_urls:
          type: array
          items:
            type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/Thumbnails'
        anti_counterfeiting:
          type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/CategoryItem'
        alerts:
          type: array
          items:
            $ref: '#/components/schemas/AlertItem'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Thumbnails:
      title: Thumbnails
      type: object
      description: Link ảnh theo từng kích thước
      properties:
        original:
          type: string
        square:
          type: string
        thumbnail:
          type: string
        small:
          type: string
        medium:
          type: string
      x-examples:
        example-1:
          original: 'http://icheckcdn.net/images/original/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
          square: 'http://icheckcdn.net/images/100x100/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
          thumbnail: 'http://icheckcdn.net/images/240x240/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
          small: 'http://icheckcdn.net/images/240x240/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
          medium: 'http://icheckcdn.net/images/375x375/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
    UserDetail:
      title: UserDetail
      type: object
      description: Thông tin chi tiết User
      properties:
        id:
          type: number
        Thông:
          type: string
    EnterpriseDetail:
      title: EnterpriseDetail
      type: object
      description: Thông tin chi tiết doanh nghiệp
      properties:
        id:
          type: number
        type:
          type: integer
        name:
          type: string
        avatar:
          type: string
        cover:
          type: string
        avatar_thumbnails:
          $ref: '#/components/schemas/Thumbnails'
        cover_thumbnails:
          $ref: '#/components/schemas/Thumbnails'
        email:
          type: string
        phone:
          type: string
        gln_code:
          type: string
        gln_type:
          type: string
        address:
          type: string
        country:
          $ref: '#/components/schemas/Country'
        city:
          $ref: '#/components/schemas/City'
        district:
          $ref: '#/components/schemas/District'
        ward:
          $ref: '#/components/schemas/Ward'
        prefix:
          type: string
        tax:
          type: string
        location:
          $ref: '#/components/schemas/Location'
        is_visible:
          type: boolean
        verify_stastus:
          type: integer
        supporter_id:
          type: number
        manager_id:
          type: number
        document:
          type: string
    Country:
      title: Country
      type: object
      description: Thông tin quốc gia
      properties:
        id:
          type: integer
        name:
          type: string
        code:
          type: string
    City:
      title: City
      type: object
      description: Thông tin tỉnh thành phố
      properties:
        id:
          type: integer
        name:
          type: string
        country_id:
          type: integer
    District:
      title: District
      type: object
      description: Thông tin Quận Huyện
      properties:
        id:
          type: integer
        name:
          type: string
        city_id:
          type: integer
    Ward:
      title: Ward
      type: object
      description: Thông tin Phường Xã
      properties:
        id:
          type: integer
        name:
          type: string
        district_id:
          type: integer
    Location:
      title: Location
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
      description: Tọa độ
    CategoryItem:
      title: CategoryItem
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      description: Category Item
    AlertItem:
      title: AlertItem
      type: object
      description: Alert Item
      properties:
        id:
          type: number
        title:
          type: string
        alert_level:
          type: string
        description:
          type: string
        body:
          type: string
    ProductItem:
      title: ProductItem
      type: object
      description: Product Item
      properties:
        id:
          type: integer
        name:
          type: string
          description: tên sản phẩm
        barcode:
          type: string
          description: mã barcode
        image:
          type: string
        thumbnails:
          $ref: '#/components/schemas/Thumbnails'
        owner:
          $ref: '#/components/schemas/EnterpriseDetail'
        disable_contribution:
          type: boolean
          description: tắt tính năng đóng góp
        verified:
          type: boolean
          description: đã xác thực
        visibled:
          type: boolean
          description: ẩn sản phẩm
        product_level_id:
          type: integer
        product_level_label:
          type: string
        anti_counterfeiting:
          type: string
        question_count:
          type: integer
        can_scan:
          type: boolean
        scan_count:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: integer
