openapi: 3.0.0
info:
  title: social
  version: '1.0'
servers:
  - url: 'https://api.dev.icheck.com.vn/api/v1'
paths:
  '/scan/:barcode':
    get:
      summary: Scan barcode
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetail'
              examples: {}
      operationId: scan-products
      description: ''
      tags:
        - scan
  /products:
    get:
      summary: List Products
      tags:
        - product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  rows:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductDetail'
      operationId: get-products
      parameters:
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: string
            example: '-id'
          in: query
          name: order
          description: ''
        - schema:
            type: number
          in: query
          name: owner_id
          description: là id của doanh nghiệp sở hữu
        - schema:
            type: string
          in: query
          name: category_id
          description: id của danh mục
        - schema:
            type: string
          in: query
          name: search
          description: Tìm kiếm theo tên hoặc mã barcode
        - schema:
            type: string
          in: query
          name: enterprise_search
          description: Tìm theo tên hoặc mã doanh nghiệp sở hữu
        - schema:
            type: string
          in: query
          name: ids
          description: 'nằm trong danh sách id, vd: 123,234,345'
        - schema:
            type: string
          in: query
          name: not_ids
          description: 'ngoài trừ các id, vd: 123,234,345'
        - schema:
            type: boolean
          in: query
          name: verified
          description: đã xác thực
        - schema:
            type: string
            enum:
              - 1
              - 2
              - 3
          in: query
          name: scan_state
          description: 'trạng thái quét - 1: cho quét, 2: không cho quét, 3: ẩn do doanh nghiệp yêu cầu'
        - schema:
            type: number
            enum:
              - 1
              - 0
          in: query
          name: empty_image
          description: 'không có ảnh - 1: đúng, 2: sai'
        - schema:
            type: number
          in: query
          name: empty_name
          description: 'không có tên - 1: đúng, 2: sai'
        - schema:
            type: number
          in: query
          name: empty_owner
          description: 'không có doanh nghiệp sở hữu - 1: đúng, 2: sai'
        - schema:
            type: number
          in: query
          name: empty_price
          description: 'không có giá - 1: đúng, 2: sai'
        - schema:
            type: number
          in: query
          name: empty_category
          description: 'không thuộc danh mục - 1: đúng, 2: sai'
      description: Danh sách sản phẩm iCheck
  '/products/:id':
    get:
      summary: Get Products By Id
      tags:
        - product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetail'
      operationId: 'get-products-:id'
      description: ''
  '/products/barcode/:barcode':
    get:
      summary: Get Product By barcode
      tags:
        - product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetail'
      operationId: get-products-barcode
    parameters: []
components:
  schemas:
    ProductDetail:
      title: ProductDetail
      type: object
      description: Thông tin chi tiết sản phẩm
      x-examples:
        example-1: {}
      properties:
        id:
          type: integer
        name:
          type: string
        barcode:
          type: string
        price:
          type: number
        image:
          type: string
        thumbnails:
          $ref: '#/components/schemas/Thumbnails'
        owner:
          $ref: '#/components/schemas/EnterpriseDetail'
        vendor:
          $ref: '#/components/schemas/EnterpriseDetail'
        distributors:
          type: array
          items:
            $ref: '#/components/schemas/EnterpriseDetail'
        disable_contribution:
          type: boolean
        scan_count:
          type: integer
        scan_status:
          type: boolean
        verified:
          type: boolean
        is_visible:
          type: boolean
        certificates:
          type: array
          items:
            $ref: '#/components/schemas/Thumbnails'
        informations:
          type: array
          items:
            type: string
    Thumbnails:
      title: Thumbnails
      type: object
      description: Link ảnh theo từng kích thước
      properties:
        original:
          type: string
        square:
          type: string
        thumbnail:
          type: string
        small:
          type: string
        medium:
          type: string
      x-examples:
        example-1:
          original: 'http://icheckcdn.net/images/original/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
          square: 'http://icheckcdn.net/images/100x100/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
          thumbnail: 'http://icheckcdn.net/images/240x240/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
          small: 'http://icheckcdn.net/images/240x240/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
          medium: 'http://icheckcdn.net/images/375x375/-TheHulk/652348943e/1486178285_1709fdfea0554dc7b4547614c5182ad3_829619.jpg'
    UserDetail:
      title: UserDetail
      type: object
      description: Thông tin chi tiết User
      properties:
        id:
          type: number
        Thông:
          type: string
    EnterpriseDetail:
      title: EnterpriseDetail
      type: object
      description: Thông tin chi tiết doanh nghiệp
      properties:
        id:
          type: number
        type:
          type: integer
        name:
          type: string
        avatar:
          type: string
        cover:
          type: string
        avatar_thumbnails:
          $ref: '#/components/schemas/Thumbnails'
        cover_thumbnails:
          $ref: '#/components/schemas/Thumbnails'
        email:
          type: string
        phone:
          type: string
        gln_code:
          type: string
        gln_type:
          type: string
        address:
          type: string
        country:
          $ref: '#/components/schemas/Country'
        city:
          $ref: '#/components/schemas/City'
        district:
          $ref: '#/components/schemas/District'
        ward:
          $ref: '#/components/schemas/Ward'
        prefix:
          type: string
        tax:
          type: string
        location:
          $ref: '#/components/schemas/Location'
        is_visible:
          type: boolean
        verify_stastus:
          type: integer
        supporter_id:
          type: number
        manager_id:
          type: number
        document:
          type: string
    Country:
      title: Country
      type: object
      description: Thông tin quốc gia
      properties:
        id:
          type: integer
        name:
          type: string
        code:
          type: string
    City:
      title: City
      type: object
      description: Thông tin tỉnh thành phố
      properties:
        id:
          type: integer
        name:
          type: string
        country_id:
          type: integer
    District:
      title: District
      type: object
      description: Thông tin Quận Huyện
      properties:
        id:
          type: integer
        name:
          type: string
        city_id:
          type: integer
    Ward:
      title: Ward
      type: object
      description: Thông tin Phường Xã
      properties:
        id:
          type: integer
        name:
          type: string
        district_id:
          type: integer
    Location:
      title: Location
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
      description: Tọa độ
